### PR TITLE
Fixed image placeholder bug

### PR DESCRIPTION
**Pull request by singhgursagar**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

### CODE REVIEW

**Comment by vanessa-cooper** [comment]
Thanks @singhgursagar, I'll review the changes right away!

**Review by vanessa-cooper — CHANGES_REQUESTED** [review]
Make sure all checks pass, only then you can merge the PR.

**Review by vanessa-cooper — APPROVED** [review]
Excellent job @singhgursagar! You're now able to merge the PR.

**Comment by singhgursagar** [comment]
Screenshot of fixed bug
Screen Shot 2022-08-09 at 3 23 38 AM

**Pull request merged**
